export const InputType={
    text:'text',
    email:'email',
    password:'password',
    number:'number',
    dropdown:'dropdown',
    checkbox:'checkbox',
    color:'color',
    date:'date',
    datetimeLocal:'datetime-local',
    file:'file',
    hidden:'hidden',
    radioGroup:'radio',
    month:'month',
    range:'range',
    time:'time',
    url:'url',
    week:'week'
}